# -*- coding: utf-8 -*-
"""Social domain logic, brief validation, eligibility and persistence module."""
from app.core.social.brief_eligibility import (
    EligibleSocialBriefInput,
    EligibleSocialBriefKeyword,
    SocialBriefEligibilityError,
    validate_social_brief_eligibility,
)
from app.core.social.brief_service import (
    SocialBriefNotFoundError,
    SocialBriefRunNotFoundError,
    create_social_brief,
    get_social_brief,
    list_social_briefs,
    social_brief_to_response,
)
from app.core.social.brief_validation import (
    SocialBriefValidationError,
    ValidatedSocialBriefInput,
    ValidatedSocialBriefTarget,
    validate_social_brief_request,
)
from app.core.social.category_contract import (
    CANONICAL_CATEGORY_TYPES,
    SocialCategoryOutputValidationError,
    ValidatedSocialCategory,
    get_social_category_response_schema,
    validate_social_category_output,
)
from app.core.social.category_flow import (
    CategoryKeywordSnapshot,
    SocialCategoryFlowError,
    SocialCategoryGenerationStart,
    begin_social_category_generation,
)
from app.core.social.category_persistence import (
    PersistedSocialCategoriesResult,
    PersistedSocialCategory,
    SocialCategoryPersistenceError,
    load_completed_social_categories,
    persist_social_categories,
)
from app.core.social.idea_contract import (
    IdeaTargetSpec,
    SocialIdeaFilterResult,
    SocialIdeaOutputValidationError,
    ValidatedSocialIdea,
    build_social_idea_response_schema,
    filter_social_idea_output,
    validate_idea_against_brief,
    validate_idea_target_specs,
    validate_social_idea_output,
)
from app.core.social.idea_flow import (
    SocialIdeaCategorySnapshot,
    SocialIdeaFlowError,
    SocialIdeaGenerationStart,
    begin_social_idea_generation,
)
from app.core.social.idea_persistence import (
    PersistedSocialIdea,
    PersistedSocialIdeasResult,
    SocialIdeaCategoryPlanSnapshot,
    SocialIdeaPersistenceError,
    SocialIdeaPlanSnapshot,
    extract_social_idea_plan_snapshot,
    persist_social_ideas,
)
from app.core.social.idea_worker_input import (
    SocialIdeaWorkerInputError,
    SocialIdeaWorkerPreparation,
    prepare_social_idea_worker_inputs,
)
from app.core.social.idea_orchestration import (
    SocialIdeaHeartbeatError,
    SocialIdeaOrchestrationError,
    SocialIdeaOrchestrationResult,
    run_social_idea_generation,
)
from app.core.social.idea_planner import (
    IdeaCategoryPlan,
    IdeaPlanValidationError,
    IdeaTargetQuota,
    SocialIdeaGenerationPlan,
    build_social_idea_generation_plan,
)
from app.core.social.idea_read import (
    SocialIdeaCoverage,
    SocialIdeaReadError,
    SocialIdeaReadItem,
    SocialIdeaReadNotFoundError,
    SocialIdeaReadResult,
    SocialIdeaWarning,
    load_social_idea_result,
)
from app.core.social.idea_retry_planner import (
    IdeaRetryAssignment,
    IdeaRetryPlanError,
    SocialIdeaRetryPlan,
    build_social_idea_retry_plan,
)
from app.core.social.idea_retry_flow import (
    SocialIdeaRetryFlowError,
    SocialIdeaRetryStart,
    begin_social_idea_retry,
)
from app.core.social.idea_retry_snapshot import (
    SocialIdeaRetryPlanSnapshot,
    SocialIdeaRetrySnapshotError,
    extract_social_idea_retry_plan_snapshot,
)
from app.core.social.idea_retry_worker_input import (
    SocialIdeaRetryWorkerInputError,
    SocialIdeaRetryWorkerPreparation,
    prepare_social_idea_retry_worker_inputs,
)
from app.core.social.idea_retry_persistence import (
    PersistedSocialIdeaRetryResult,
    PersistedSocialIdeasRetryResult,
    SocialIdeaRetryPersistenceError,
    persist_social_idea_retry_results,
    persist_social_ideas_retry,
)
from app.core.social.idea_retry_orchestration import (
    SocialIdeaRetryHeartbeatError,
    SocialIdeaRetryOrchestrationError,
    SocialIdeaRetryOrchestrationResult,
    run_social_idea_retry_generation,
)
from app.core.social.idea_retry_read import (
    load_social_idea_retry_result,
)
from app.core.social.content_contract import (
    CONTENT_CONTRACT_INVALID_DURATION,
    CONTENT_CONTRACT_INVALID_FORMAT_PAYLOAD,
    CONTENT_CONTRACT_INVALID_HASHTAGS,
    CONTENT_CONTRACT_INVALID_INPUT,
    CONTENT_CONTRACT_INVALID_TARGET,
    CONTENT_CONTRACT_INVALID_TEXT,
    CONTENT_CONTRACT_INVALID_TIMELINE,
    ContentTargetSpec,
    SocialContentOutputValidationError,
    ValidatedCarouselPayload,
    ValidatedCarouselSlide,
    ValidatedHook,
    ValidatedSocialContent,
    ValidatedThreadPayload,
    ValidatedThreadPost,
    ValidatedVideoPayload,
    ValidatedVideoSegment,
    VOICEOVER_MAX_WORDS_PER_SEC,
    VOICEOVER_MIN_WORDS_PER_SEC,
    VOICEOVER_WARNING_REASON_CODE,
    build_social_content_response_schema,
    render_legacy_scenario,
    serialize_content_format_payload,
    validate_content_target_spec,
    validate_social_content_output,
)
from app.core.social.content_quality import (
    SocialContentGroundingContext,
    SocialContentQualityDecision,
    SocialContentQualityError,
    evaluate_social_content_quality,
    find_social_content_ungrounded_claims,
)
from app.core.social.content_persistence import (
    PersistedSocialContent,
    PersistedSocialContentResult,
    SocialContentPersistenceError,
    persist_social_content,
    validate_and_build_persisted_social_content,
    validate_social_content_attempt_coverage,
)
from app.core.social.content_worker_input import (
    CONTENT_WORKER_INPUT_INCONSISTENT,
    CONTENT_WORKER_INPUT_INVALID,
    SocialContentRequestSnapshot,
    SocialContentWorkItem,
    SocialContentWorkerInputError,
    SocialContentWorkerPreparation,
    extract_social_content_request_snapshot,
    prepare_social_content_worker_inputs,
)
from app.core.social.content_item_execution import (
    CONTENT_EXECUTION_INCONSISTENT,
    CONTENT_INPUT_INVALID,
    CONTENT_OUTPUT_INVALID,
    CONTENT_PROVIDER_ERROR,
    CONTENT_QUALITY_INVALID,
    CONTENT_REPAIR_INPUT_INVALID,
    CONTENT_REPAIR_OUTPUT_INVALID,
    CONTENT_REPAIR_PROVIDER_ERROR,
    SocialContentItemExecutionError,
    SocialContentItemExecutionResult,
    execute_social_content_work_item,
)
from app.core.social.content_batch_execution import (
    BATCH_WARNING_REASON_ALLOWLIST,
    SocialContentBatchExecutionError,
    SocialContentBatchExecutionResult,
    SocialContentBatchWarning,
    execute_social_content_batch,
)
from app.core.social.content_orchestration import (
    SocialContentHeartbeatError,
    SocialContentOrchestrationError,
    SocialContentOrchestrationResult,
    run_social_content_generation,
)
from app.core.social.content_flow import (
    CONTENT_ASSIGNMENT_CHANGED,
    CONTENT_ATTEMPT_REQUEST_MISMATCH,
    CONTENT_ATTEMPT_SNAPSHOT_INVALID,
    CONTENT_BRIEF_NOT_FOUND,
    CONTENT_BRIEF_NOT_LOCKED,
    CONTENT_BRIEF_STALE,
    CONTENT_GROUNDING_INVALID,
    CONTENT_IDEA_NOT_ELIGIBLE,
    CONTENT_IDEAS_INVALID,
    CONTENT_INVALID_INPUT,
    SocialContentFlowError,
    SocialContentGenerationStart,
    begin_social_content_generation,
)
from app.core.social.content_read import (
    CONTENT_ATTEMPT_NOT_FOUND,
    CONTENT_READ_INCONSISTENT,
    SocialContentAttemptReadResult,
    SocialContentReadError,
    SocialContentReadNotFoundError,
    SocialContentReadWarning,
    load_social_content_result,
)



def __getattr__(name: str):
    if name == "SOCIAL_CATEGORY_RESPONSE_SCHEMA":
        return get_social_category_response_schema()
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")


__all__ = [
    "SocialBriefValidationError",
    "ValidatedSocialBriefInput",
    "ValidatedSocialBriefTarget",
    "validate_social_brief_request",
    "SocialBriefEligibilityError",
    "EligibleSocialBriefKeyword",
    "EligibleSocialBriefInput",
    "validate_social_brief_eligibility",
    "SocialBriefNotFoundError",
    "SocialBriefRunNotFoundError",
    "create_social_brief",
    "get_social_brief",
    "list_social_briefs",
    "social_brief_to_response",
    "SocialCategoryFlowError",
    "CategoryKeywordSnapshot",
    "SocialCategoryGenerationStart",
    "begin_social_category_generation",
    "CANONICAL_CATEGORY_TYPES",
    "SocialCategoryOutputValidationError",
    "ValidatedSocialCategory",
    "get_social_category_response_schema",
    "validate_social_category_output",
    "SOCIAL_CATEGORY_RESPONSE_SCHEMA",
    "SocialCategoryPersistenceError",
    "PersistedSocialCategory",
    "PersistedSocialCategoriesResult",
    "persist_social_categories",
    "load_completed_social_categories",
    "IdeaPlanValidationError",
    "IdeaTargetQuota",
    "IdeaCategoryPlan",
    "SocialIdeaGenerationPlan",
    "build_social_idea_generation_plan",
    "IdeaTargetSpec",
    "SocialIdeaOutputValidationError",
    "ValidatedSocialIdea",
    "build_social_idea_response_schema",
    "validate_idea_target_specs",
    "validate_social_idea_output",
    "SocialIdeaFilterResult",
    "filter_social_idea_output",
    "validate_idea_against_brief",
    "SocialIdeaFlowError",
    "SocialIdeaCategorySnapshot",
    "SocialIdeaGenerationStart",
    "begin_social_idea_generation",
    "SocialIdeaPersistenceError",
    "PersistedSocialIdea",
    "PersistedSocialIdeasResult",
    "persist_social_ideas",
    "SocialIdeaCategoryPlanSnapshot",
    "SocialIdeaPlanSnapshot",
    "extract_social_idea_plan_snapshot",
    "SocialIdeaWorkerInputError",
    "SocialIdeaWorkerPreparation",
    "prepare_social_idea_worker_inputs",
    "SocialIdeaHeartbeatError",
    "SocialIdeaOrchestrationError",
    "SocialIdeaOrchestrationResult",
    "run_social_idea_generation",
    "SocialIdeaReadError",
    "SocialIdeaReadNotFoundError",
    "SocialIdeaCoverage",
    "SocialIdeaWarning",
    "SocialIdeaReadItem",
    "SocialIdeaReadResult",
    "load_social_idea_result",
    "IdeaRetryAssignment",
    "SocialIdeaRetryPlan",
    "IdeaRetryPlanError",
    "build_social_idea_retry_plan",
    "SocialIdeaRetryFlowError",
    "SocialIdeaRetryStart",
    "begin_social_idea_retry",
    "SocialIdeaRetrySnapshotError",
    "SocialIdeaRetryPlanSnapshot",
    "extract_social_idea_retry_plan_snapshot",
    "SocialIdeaRetryWorkerInputError",
    "SocialIdeaRetryWorkerPreparation",
    "prepare_social_idea_retry_worker_inputs",
    "SocialIdeaRetryPersistenceError",
    "PersistedSocialIdeaRetryResult",
    "PersistedSocialIdeasRetryResult",
    "persist_social_idea_retry_results",
    "persist_social_ideas_retry",
    "SocialIdeaRetryHeartbeatError",
    "SocialIdeaRetryOrchestrationError",
    "SocialIdeaRetryOrchestrationResult",
    "run_social_idea_retry_generation",
    "load_social_idea_retry_result",
    "CONTENT_CONTRACT_INVALID_DURATION",
    "CONTENT_CONTRACT_INVALID_FORMAT_PAYLOAD",
    "CONTENT_CONTRACT_INVALID_HASHTAGS",
    "CONTENT_CONTRACT_INVALID_INPUT",
    "CONTENT_CONTRACT_INVALID_TARGET",
    "CONTENT_CONTRACT_INVALID_TEXT",
    "CONTENT_CONTRACT_INVALID_TIMELINE",
    "ContentTargetSpec",
    "SocialContentOutputValidationError",
    "ValidatedCarouselPayload",
    "ValidatedCarouselSlide",
    "ValidatedHook",
    "ValidatedSocialContent",
    "ValidatedThreadPayload",
    "ValidatedThreadPost",
    "ValidatedVideoPayload",
    "ValidatedVideoSegment",
    "VOICEOVER_MAX_WORDS_PER_SEC",
    "VOICEOVER_MIN_WORDS_PER_SEC",
    "VOICEOVER_WARNING_REASON_CODE",
    "build_social_content_response_schema",
    "render_legacy_scenario",
    "serialize_content_format_payload",
    "validate_content_target_spec",
    "validate_social_content_output",
    "SocialContentGroundingContext",
    "SocialContentQualityDecision",
    "SocialContentQualityError",
    "find_social_content_ungrounded_claims",
    "evaluate_social_content_quality",
    "PersistedSocialContent",
    "PersistedSocialContentResult",
    "SocialContentPersistenceError",
    "persist_social_content",
    "validate_and_build_persisted_social_content",
    "SocialContentWorkerInputError",
    "CONTENT_WORKER_INPUT_INVALID",
    "CONTENT_WORKER_INPUT_INCONSISTENT",
    "SocialContentRequestSnapshot",
    "SocialContentWorkItem",
    "SocialContentWorkerPreparation",
    "extract_social_content_request_snapshot",
    "prepare_social_content_worker_inputs",
    "CONTENT_EXECUTION_INCONSISTENT",
    "CONTENT_INPUT_INVALID",
    "CONTENT_OUTPUT_INVALID",
    "CONTENT_PROVIDER_ERROR",
    "CONTENT_QUALITY_INVALID",
    "CONTENT_REPAIR_INPUT_INVALID",
    "CONTENT_REPAIR_OUTPUT_INVALID",
    "CONTENT_REPAIR_PROVIDER_ERROR",
    "SocialContentItemExecutionError",
    "SocialContentItemExecutionResult",
    "execute_social_content_work_item",
    "BATCH_WARNING_REASON_ALLOWLIST",
    "SocialContentBatchExecutionError",
    "SocialContentBatchExecutionResult",
    "SocialContentBatchWarning",
    "execute_social_content_batch",
    "SocialContentHeartbeatError",
    "SocialContentOrchestrationError",
    "SocialContentOrchestrationResult",
    "run_social_content_generation",
    "validate_social_content_attempt_coverage",
    "CONTENT_ASSIGNMENT_CHANGED",
    "CONTENT_ATTEMPT_REQUEST_MISMATCH",
    "CONTENT_ATTEMPT_SNAPSHOT_INVALID",
    "CONTENT_BRIEF_NOT_FOUND",
    "CONTENT_BRIEF_NOT_LOCKED",
    "CONTENT_BRIEF_STALE",
    "CONTENT_GROUNDING_INVALID",
    "CONTENT_IDEA_NOT_ELIGIBLE",
    "CONTENT_IDEAS_INVALID",
    "CONTENT_INVALID_INPUT",
    "SocialContentFlowError",
    "SocialContentGenerationStart",
    "begin_social_content_generation",
    "CONTENT_ATTEMPT_NOT_FOUND",
    "CONTENT_READ_INCONSISTENT",
    "SocialContentAttemptReadResult",
    "SocialContentReadError",
    "SocialContentReadNotFoundError",
    "SocialContentReadWarning",
    "load_social_content_result",
]



